name: Playwright Tests
on: 
    push:
        branches: [main]
jobs:
    playwrighttests:
        runs-on: ubuntu-latest
        container:
          image: mcr.microsoft.com/playwright:v1.47.2-focal
          env:
            ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        steps:
            - name : Checkout repository
              uses: actions/checkout@v2
            - name: Run tests
              run: |
               echo "Start the shopping application"
               ./shopping-store-windows-386.exe
               echo "Install dependecies from lockfile"
               npm ci
               echo "Run playwright tests"
               npm run test:ci